import React from "react";
import {
  FacebookShareButton,
  TwitterShareButton,
  LinkedinShareButton,
  WhatsappShareButton,
  TelegramShareButton,
  EmailShareButton,
  FacebookIcon,
  TwitterIcon,
  LinkedinIcon,
  WhatsappIcon,
  TelegramIcon,
  EmailIcon,
} from "react-share";
import { IoClose } from "react-icons/io5";

interface SocialShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  url: string;
  title?: string;
  description?: string;
}

const SocialShareModal: React.FC<SocialShareModalProps> = ({
  isOpen,
  onClose,
  url,
  title = "Business AI Plan",
  description = "Check out this amazing business plan generated by AI!",
}) => {
  if (!isOpen) return null;

  const shareUrl = url;
  const shareTitle = title;
  const shareDescription = description;

  const socialPlatforms = [
    {
      name: "Facebook",
      component: FacebookShareButton,
      icon: FacebookIcon,
      color: "bg-blue-600 hover:bg-blue-700 shadow-md",
    },
    {
      name: "Twitter",
      component: TwitterShareButton,
      icon: TwitterIcon,
      color: "bg-sky-500 hover:bg-sky-600 shadow-md",
    },
    {
      name: "LinkedIn",
      component: LinkedinShareButton,
      icon: LinkedinIcon,
      color: "bg-blue-700 hover:bg-blue-800 shadow-md",
    },
    {
      name: "WhatsApp",
      component: WhatsappShareButton,
      icon: WhatsappIcon,
      color: "bg-green-500 hover:bg-green-600 shadow-md",
    },
    {
      name: "Telegram",
      component: TelegramShareButton,
      icon: TelegramIcon,
      color: "bg-blue-500 hover:bg-blue-600 shadow-md",
    },
    {
      name: "Email",
      component: EmailShareButton,
      icon: EmailIcon,
      color: "bg-info hover:bg-info/90 shadow-md",
    },
  ];

  const handleCopyLink = async () => {
    try {
      await navigator.clipboard.writeText(shareUrl);
      // You can add a toast notification here
      alert("Link copied to clipboard!");
    } catch (err) {
      console.error("Failed to copy link: ", err);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-[20px] shadow-2xl max-w-xl w-full mx-4 transform transition-all animate-slide-up">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-gray-200">
          <h2 className="text-xl font-semibold text-accent">
            Share Business Plan
          </h2>
          <button
            onClick={onClose}
            className="p-2 hover:bg-card rounded-full transition-colors"
          >
            <IoClose className="w-5 h-5 text-info" />
          </button>
        </div>

        {/* Content */}
        <div className="p-6">
          <p className="text-info mb-6 text-center">
            Share this business plan with your network
          </p>

          {/* Social Media Buttons */}
          <div className="grid grid-cols-3 gap-4 mb-6">
            {socialPlatforms.map((platform) => {
              const ShareButton = platform.component;
              const Icon = platform.icon;

              return (
                <ShareButton
                  key={platform.name}
                  url={shareUrl}
                  title={shareTitle}
                  summary={shareDescription}
                  className="w-full"
                >
                  <div
                    className={`${platform.color} text-white p-4 rounded-sm flex flex-col items-center justify-center space-y-2 hover:scale-105 transition-all duration-300 cursor-pointer`}
                  >
                    <Icon size={32} round />
                    <span className="text-sm font-medium">{platform.name}</span>
                  </div>
                </ShareButton>
              );
            })}
          </div>

          {/* Copy Link Section */}
          <div className="border-t border-gray-200 pt-4">
            <p className="text-sm text-info mb-3">Or copy the link:</p>
            <div className="flex items-center space-x-2">
              <input
                type="text"
                value={shareUrl}
                readOnly
                className="flex-1 px-3 py-2 border border-gray-300 rounded-sm text-sm bg-card focus:outline-none focus:ring-2 focus:ring-primary/20"
              />
              <button
                onClick={handleCopyLink}
                className="px-4 py-2 bg-primary/80 text-white rounded-sm hover:bg-primary transition-all duration-300 text-sm font-medium shadow-md hover:scale-[1.02]"
              >
                Copy
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SocialShareModal;
