import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import { openSans } from "@/fonts/fonts";
import { Suspense } from "react";
import { Toaster } from "sonner";
import ReduxProvider from "@/redux/Provider";
import Loading from "@/components/Others/Loading";
import StripeProvider from "@/components/StripeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
});

export const metadata: Metadata = {
  title: "AI Business Plan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}  className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} antialiased`}>
        <ReduxProvider>
          <StripeProvider>
            <Toaster position="top-center" expand={true} richColors />
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </StripeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
